on:
  release:
    types:
      - released

jobs:
  publish:
    name: Publish Release
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 16
      - name: Install dependencies
        run: yarn install
      - name: Publish to VSCode Extension Marketplace
        uses: lannonbr/vsce-action@3.0.0
        with:
          args: "publish -p $PUBLISHER_TOKEN"
        env:
          PUBLISHER_TOKEN: ${{ secrets.PUBLISHER_TOKEN }}
