on:
  push:
    branches:
      - master
jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 16
      - name: Install dependencies
        run: yarn install
      - name: Run Linting
        run: yarn lint

  release:
    name: Github Release
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 16
      - name: Install dependencies
        run: yarn install
      - name: Github Release
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_GITHUB_TOKEN }}
        run: npx semantic-release

  publish:
    name: Publish Release
    runs-on: ubuntu-18.04
    needs: release
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 16
      - name: Install dependencies
        run: yarn install
      - name: Publish to VSCode Extension Marketplace
        uses: lannonbr/vsce-action@3.0.0
        with:
          args: "publish -p $PUBLISHER_TOKEN"
        env:
          PUBLISHER_TOKEN: ${{ secrets.PUBLISHER_TOKEN }}
